/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.services.UserBookingService;

import java.io.IOException;
import java.util.Scanner;

public class App {
        System.out.println("Running train booking system");
        Scanner scanner =new Scanner(System.in);
        int options =0;
        UserBookingService userBookingService;
        try{
            userBookingService=new UserBookingService();
        } catch (IOException ex) {
                System.out.println("Something went wrong");
                return;
        }
        while(options!=7){

    }

}
